export default [
  {
    id: 1,
    restaurant_name: "Grab e cuppa",
    user_activity: "Login",
    admin_name: "Kaylin Mbappe",
    user_name: "Dionne Owens",
    date: "2022-08-21",
    time: "10:00 AM",
    email: "Asd@gmail.com",
    name: "Admin,Approved,Grab e cuppa",
  },
  {
    id: 2,
    restaurant_name: "Sulter dine",
    user_activity: "Visited",
    admin_name: "Kaylin Mbappe",
    user_name: "Rojas Luna",
    date: "2023-08-04",
    time: "10:00 AM",
    email: "Asd@gmail.com",
    name: "Admin,Approved,Sulter dine",
  },
  {
    id: 3,
    restaurant_name: "Kacchi Bhai",
    user_activity: "Print",
    user_name: "Sarah Craig",
    admin_name: "Kaylin Mbappe",
    date: "2019-09-23",
    time: "10:00 AM",
    email: "Asd@gmail.com",
    name: "Admin,Approved,Kacchi Bhai",
  },
  {
    id: 4,
    restaurant_name: "Sulter dine",
    user_activity: "Download",
    user_name: "Byers Mccoy",
    admin_name: "Kaylin Mbappe",
    date: "2014-02-21",
    time: "10:00 AM",
    email: "Asd@gmail.com",
    name: "Admin,Rejected,Sulter dine",
  },
];
