import { Roboto } from "next/font/google";
import "../globals.css";
import Sidebar from "@/components/Sidebar";
import Header from "@/components/Header";
import { CookiesProvider } from "next-client-cookies/server";
import { Toaster } from "@/components/ui/toaster";

// const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({
  weight: ["100", "300", "400", "500", "700", "900"],
  subsets: ["latin"],
});

export const metadata = {
  title: "M3 Super admin dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={roboto.className}>
        <CookiesProvider>
          <div className={"w-[98%] mx-auto"}>
            <Toaster />
            <div className={"grid col-span-12"}>
              <Header />
            </div>
            <div className={"grid grid-cols-12 gap-24"}>
              <div className="col-span-2">
                <div className={"hidden md:block relative"}>
                  <Sidebar />
                </div>
              </div>

              <div className={"col-span-12 md:col-span-10 mt-28"}>
                {children}
              </div>
            </div>
          </div>
        </CookiesProvider>
      </body>
    </html>
  );
}
