name: Dev server update CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Execute remote SSH commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.STAGING_USER }}
          password: ${{ secrets.STAGING_PASS }}
          script: |
            cd /var/www/mmm_superadmin
            echo ${{ secrets.STAGING_PASS }} | sudo -S git pull
            echo ${{ secrets.STAGING_PASS }} | sudo -S npm i --legacy-peer-deps
            echo ${{ secrets.STAGING_PASS }} | sudo -S npm i sharp
            echo ${{ secrets.STAGING_PASS }} | sudo -S npm run build
            pm2 restart mmm_superadmin
            echo ${{ secrets.STAGING_PASS }} | sudo -S systemctl restart nginx

